#  .pre
#  build
#  test
#  deploy
#  .post

#build-simulation:
#  tags:
#    - ci
#  stage: build
#  script:
#  - sudo make all


build:
  tags:
    - ci
  stage: test
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

