#  .pre
#  build
#  test
#  deploy
#  .post
image: docker:latest

services:
  - name: docker:dind
    entrypoint: [ "env", "-u", "DOCKER_HOST" ]
    command: [ "dockerd-entrypoint.sh" ]


build:
  stage: build
  before_script:
    #- apt-get update && apt-get install make
    #- apt-get install -y gcc
    - apk update && apk add git
    - apk add make
    - apk add python3
   # - apk add py3-pip ????+?????
  script:
    - make ci
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths:
    - builds/*

#runner_healthy:
#  stage: .pre
#  script:
#    - echo "Runner Works!"

#build:
#  stage: test
#  before_script:
#    #- apt-get update && apt-get install make
#    #- apt-get install -y gcc
#    - apt-get update && apt-get install -y git
#  script:
#    - make ci
# #   - sudo make clean
# #   - sudo rm builds/debug/*
# #   - sudo rm builds/release/*
#  artifacts:
#      paths:
#      - builds/*
#build-simulation:
#  tags:
#    - ci
#  stage: build
#  script:
#  - sudo make all

#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main