variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image: docker:20.10.5
  services:
    - name: docker:dind
      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
      command: [ "dockerd-entrypoint.sh" ]
  stage: build
  before_script:
    - apk update && apk add git
    - apk add bash
    - apk add make
    - apk add python3
  script:
    #- sleep 1h
    - make ci
  variables:
    DOCKER_HOST: tcp://docker:2375/ #just to fix dind issue
    DOCKER_DRIVER: overlay2         #just to fix dind issue
    DOCKER_TLS_CERTDIR: ""          #just to fix dind issue
  artifacts:
    paths:
      - builds/*


build-simulation:
  image: ubuntu:20.04
  tags:
    - uind
  stage: build
  before_script:
    - apt update -y && apt install -y git
    - apt install -y make
    - apt install -y gcc
    - apt install -y python3
    - git submodule update --init --recursive
  script:
    - make all


#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main
