#  .pre
#  build
#  test
#  deploy
#  .post

runner_healthy:
  stage: .pre
  tags:
    - ci
  script:
    - echo "Runner Works!"

build-simulation:
  tags:
    - ci
  stage: build
  script:
  - sudo make all


build:
  tags:
    - ci
  stage: test
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main