#  .pre
#  build
#  test
#  deploy
#  .post

build-simulation:
  tags:
    - ci
  stage: build
  script:
  #- git clone --recurse-submodules https://github.com//Nitrokey/nitrokey-fido2-firmware
  - cd nitrokey-fido2-firmware
  - sudo make all


build:
  tags:
    - ci
  stage: build
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

