#  .pre
#  build
#  test
#  deploy
#  .post
image: docker:stable
services:
  - docker:dind

#runner_healthy:
#  stage: .pre
#  script:
#    - echo "Runner Works!"

build:
  stage: test
  before_script:
    - apt-get update && apt-get install make
    - apt-get install -y gcc
    - apt-get install -y git
  script:
    - make ci
 #   - sudo make clean
 #   - sudo rm builds/debug/*
 #   - sudo rm builds/release/*
  artifacts:
      paths:
      - builds/*
#build-simulation:
#  tags:
#    - ci
#  stage: build
#  script:
#  - sudo make all

#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main