#  .pre
#  build
#  test
#  deploy
#  .post


simulation:
  tags:
    - ci
  stage: build
  script:
  - git clone --recurse-submodules https://github.com//Nitrokey/nitrokey-fido2-firmware
  - cd nitrokey-fido2-firmware
  - make all


build:
  tags:
    - ci
  stage: build
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

  # CI_BUILDS_DIR The top-level directory where builds are executed. ?