#  .pre
#  build
#  test
#  deploy
#  .post
image: docker:20.10.5

services:
  - name: docker:dind
    entrypoint: [ "env", "-u", "DOCKER_HOST" ]
    command: [ "dockerd-entrypoint.sh" ]

#runner_healthy:
#  stage: .pre
#  script:
#    - echo "Runner Works!"

build:
  stage: build
  before_script:
    - apk update && apk add git
    - apk add make
    - apk add python3
  script:
    - make ci
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths:
    - builds/*

#build-simulation:
#  stage: test
#  script:
#    - apk update && apk add git
#    - apk add make
#    - apk add python3
#    - git submodule update --init --recursive
#    - ls
#    - make all
#  variables:
#    DOCKER_HOST: tcp://docker:2375/
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""
build-simulation:
  stage: test
  script:
  - sudo make all
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""



#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main
