#  .pre
#  build
#  test
#  deploy
#  .post

pipline_test:
  stage: .pre
  tags:
    - ci
  script:
    - echo "Pipline Works!"

build-simulation:
  tags:
    - ci
  stage: build
  script:
  - sudo make all
  - sudo ./main


build:
  tags:
    - ci
  stage: test
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

