#  .pre
#  build
#  test
#  deploy
#  .post

build:
  tags:
    - ci
  stage: build
  script:
    - sudo make ci
  artifacts:
      paths:
      - builds/*

  # CI_BUILDS_DIR The top-level directory where builds are executed. ?