#  .pre
#  build
#  test
#  deploy
#  .post

#pipline_test:
#  stage: .pre
#  script:
#    - echo "Pipline Works!!!"




build:
  image: docker:latest
  services:
    - name: docker:dind
      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
      command: [ "dockerd-entrypoint.sh" ]
  stage: build
  before_script:
    - apk update && apk add git
    - apk add bash
    - apk add make
    - apk add python3
  script:
    #- sleep 1h
    - make ci
  variables:
    GIT_STRATEGY: clone
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths:
      - builds/*


build-simulation:
  image: ubuntu:latest
  tags:
    - uind
  stage: test
  before_script:
    - apt update -y && apt install -y git
    - apt install -y make
    - apt install -y gcc
    - apt install -y python3
  script:
  - make all


#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main
