#  .pre
#  build
#  test
#  deploy
#  .post

#pipline_test:
#  stage: .pre
#  script:
#    - echo "Pipline Works!!!"


image: docker:latest

services:
  - name: docker:dind
    entrypoint: [ "env", "-u", "DOCKER_HOST" ]
    command: [ "dockerd-entrypoint.sh" ]

build:
  stage: build
  before_script:
    - apk update && apk add git
    - apk add make
    - apk add python3
  script:
    - git branch
    - git remote -v
    - git pull origin master --tags
    - make ci
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths:
      - builds/*


#build-simulation:
#  stage: test
#  before_script:
#    - apk update && apk add git
#    - apk add make
#    - apk add python3
#  script:
#  - make all
#  variables:
#    DOCKER_HOST: tcp://docker:2375/
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""


#test-simulation:
#  tags:
#    - ci
#  stage: test
#  script:
#    - sudo ./main
